openapi: 3.0.0
info:
  title: APP-API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /v1/register:
    parameters: []
    post:
      summary: Register User
      operationId: post-v1-register
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                required:
                  - token
          headers: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_message:
                    type: string
                required:
                  - error_message
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_message:
                    type: string
                    description: duplicate username
                required:
                  - error_message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                  description: sha-256 hashed password
              required:
                - username
                - password
      security: []
  /v1/login:
    post:
      summary: Login User
      operationId: post-v1-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_message:
                    type: string
                    description: wrong password/username
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                  description: sha-256 hashed password
              required:
                - username
                - password
      security: []
  /v1/conf/privileges:
    post:
      summary: Edit Privileges for User
      operationId: post-v1-conf-privileges
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userid:
                  type: integer
                access:
                  type: object
                  required:
                    - admin
                  properties:
                    admin:
                      type: boolean
                      description: if admin is true the other properties aren't needed
                    canadd:
                      type: boolean
                    speakers:
                      type: array
                      items:
                        type: integer
                    rooms:
                      type: array
                      items:
                        type: integer
              required:
                - userid
                - access
  /v1/user/getall:
    get:
      summary: Get List of all Users
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        userid:
                          type: integer
                        username:
                          type: string
              examples: {}
      operationId: get-v1-get-allUsers
    parameters: []
  /v1/room/create:
    parameters: []
    post:
      summary: ''
      operationId: post-v1-room-create
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              example-1:
                value: {}
  /v1/room/getall:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  rooms:
                    type: array
                    items:
                      $ref: '#/components/schemas/Room'
      operationId: get-v1-room-getall
  '/v1/room/get/{id}':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
      operationId: get-v1-room-get
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
components:
  schemas:
    Room:
      title: Room
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        speakers:
          type: array
          items:
            $ref: '#/components/schemas/Speaker'
        dimensions:
          type: object
          description: not used yet
          properties:
            height:
              type: number
            width:
              type: number
    Speaker:
      title: Speaker
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        position:
          type: object
          description: not used yet
          properties:
            x:
              type: number
            'y':
              type: number
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      description: ''
security:
  - Authorization: []
