openapi: 3.0.0
info:
  title: APP-API
  version: '1.0'
  contact:
    email: bylukee1@gmail.com
  description: API for communication between the MRAS WebApp/App and the Server
servers:
  - url: 'http://localhost:3000/api/v1'
paths:
  /register:
    parameters: []
    post:
      summary: Register User
      operationId: post-v1-register
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
                required:
                  - token
          headers: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/Error'
                required:
                  - error
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/Error'
                required:
                  - error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                  description: sha-256 hashed password
              required:
                - username
                - password
      security: []
  /login:
    post:
      summary: Login User
      operationId: post-v1-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                  description: sha-256 hashed password
              required:
                - username
                - password
      security: []
    parameters: []
  /user/conf/privileges:
    parameters: []
    put:
      summary: ''
      operationId: put-user-conf-privileges
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userid:
                  type: integer
                access:
                  type: object
                  required:
                    - admin
                  properties:
                    admin:
                      type: boolean
                      description: if admin is true the other properties aren't needed
                    canadd:
                      type: boolean
                    speakers:
                      type: array
                      items:
                        type: integer
                    rooms:
                      type: array
                      items:
                        type: integer
              required:
                - userid
                - access
  /user/getall:
    get:
      summary: Get List of all Users
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        userid:
                          type: integer
                        username:
                          type: string
              examples: {}
      operationId: get-v1-get-allUsers
    parameters: []
  /room/create:
    parameters: []
    post:
      summary: Create a new Room
      operationId: post-v1-room-create
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/User'
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                desciption:
                  type: string
                dimensions:
                  type: object
                  properties:
                    hieght:
                      type: number
                    width:
                      type: number
            examples:
              example-1:
                value: {}
  /room/getall:
    get:
      summary: Get all Rooms
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  rooms:
                    type: array
                    items:
                      $ref: '#/components/schemas/Room'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/Error'
      operationId: get-v1-room-getall
    parameters: []
  '/room/get/{id}':
    get:
      summary: Get Specific Room by ID
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/Error'
      operationId: get-v1-room-get
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
  '/user/get/{id}':
    get:
      summary: Get specific User by ID
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
      operationId: get-user
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
components:
  schemas:
    Room:
      title: Room
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        dimensions:
          type: object
          description: not used yet
          properties:
            height:
              type: number
            width:
              type: number
    Speaker:
      title: Speaker
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        position:
          type: object
          description: not used yet
          properties:
            x:
              type: number
            'y':
              type: number
        roomid:
          type: integer
    User:
      title: User
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
    Error:
      title: Error
      type: object
      properties:
        code:
          type: string
        message:
          type: string
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      description: ''
security:
  - Bearer: []
