server:
  jwtAccessSecret: "ABCDEF"
  jwtRefreshSecret: "ABCDEF"
  app:
    port: 3000
  client:
    port: 3001
  mysql:
    host: "192.168.0.109"
    port: 3306
    user: "mras"
    password: "Passwort123!"
    dbname: "mras"
  redis:
    host: "192.168.0.109"
    port: 6379
    password: ""
    db: 0
client:
  client-backend:
    port: 3010
    protocol: "http"
    path-playback: "/api/v1/playback"
    path-method: "/api/v1/method"
  client-client:
    port: 3020
    protocol: "http"
    path: "/api/v1/listen"
logs:
  path: "./"
  level: "DEBUG"
  maxSize: 15
  maxAge: 30