openapi: 3.0.0
info:
  title: APP-API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /test:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  test1:
                    type: string
      operationId: get-test
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                test:
                  type: string
components:
  schemas: {}
